//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLKS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DatPhong
    {
        public int MaDatPhong { get; set; }
        public Nullable<int> MaKH { get; set; }
        public Nullable<int> MaPhong { get; set; }
        public Nullable<System.DateTime> NgayDen { get; set; }
        public Nullable<System.DateTime> NgayDi { get; set; }
        public string TinhTrang { get; set; }
        public Nullable<int> ThanhToan { get; set; }
        public Nullable<int> ChiPhiPhatSinh { get; set; }
    
        public virtual KhachHang KhachHang { get; set; }
        public virtual Phong Phong { get; set; }
    }
}
